[profile.default]
solc = '0.8.26'
evm_version = 'paris'
optimizer_runs = 200
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
via_ir = true
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@bananapus/core/=lib/nana-core/src/",
    "@bananapus/core-v6/=node_modules/@bananapus/core-v6/",
    "@bananapus/permission-ids/=node_modules/@bananapus/permission-ids-v6/src/",
    "@bananapus/permission-ids-v6/=node_modules/@bananapus/permission-ids-v6/",
    "@bananapus/721-hook-v6/=node_modules/@bananapus/721-hook-v6/",
    "@bananapus/ownable-v6/=node_modules/@bananapus/ownable-v6/",
    "@bananapus/suckers-v6/=node_modules/@bananapus/suckers-v6/",
    "@bananapus/buyback-hook-v6/=node_modules/@bananapus/buyback-hook-v6/",
    "@rev-net/core-v6/=node_modules/@rev-net/core-v6/",
    "@sphinx-labs/contracts/=lib/nana-core/lib/sphinx/packages/contracts/contracts/foundry/",
    "@uniswap/permit2/=node_modules/@uniswap/permit2/",
    "@uniswap/v4-core/=node_modules/@uniswap/v4-core/",
    "@uniswap/v4-periphery/=node_modules/@uniswap/v4-periphery/",
    "@prb/math/=lib/prb-math/",
]

[profile.ci_sizes]
optimizer_runs = 200

[fuzz]
runs = 4096

[invariant]
runs = 1024
depth = 100
fail_on_revert = false

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true
