[profile.default]
solc = '0.8.28'
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@uniswap/v3-core-patched/=lib/v3-core-patched/",
    "@uniswap/v3-periphery-flattened/=lib/v3-periphery-flattened/",
    "@uniswap/v3-core/=node_modules/@uniswap/v3-core/",
    "@uniswap/permit2/=node_modules/@uniswap/permit2/",
]
# Required to avoid stack too deep for invoking INonfungiblePositionManager.position() as per https://github.com/Uniswap/v3-periphery/issues/273
via_ir = true
optimizer_runs = 1000
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.ci_sizes]
optimizer_runs = 200

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true