[profile.default]
solc = '0.8.23'
evm_version = 'paris'
optimizer_runs = 200
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
via_ir = true
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@bananapus/core=lib/nana-core/src",
    "@bananapus/permission-ids=node_modules/@bananapus/permission-ids-v6/src",
    "@uniswap/v3-core=lib/v3-core/contracts",
    "@uniswap/v3-core-patched=lib/v3-core-patched",
    "@uniswap/v3-periphery-flattened=lib/v3-periphery-flattened",
    "@uniswap/permit2=lib/permit2",
    "@prb/math=lib/prb-math",
]

[profile.ci_sizes]
optimizer_runs = 200

[fuzz]
runs = 4096

[invariant]
runs = 1024
depth = 100
fail_on_revert = false

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true
